MvcProjectCamp/Controllers/AdminCategoryController.cs
using Business.ValidationRules.FluentValidation;
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
    public class AdminCategoryController : Controller
    {
        // GET: AdminCategory

        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());

        [HttpGet]
        public ActionResult Index()
        {
            var result = categoryManager.GetAll();
            return View(result);
        }
        

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Category category)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult validationResult = categoryValidator.Validate(category);
            if (validationResult.IsValid)
            {
                categoryManager.Add(category);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult Delete(int categoryId)
        {
            var result = categoryManager.GetById(categoryId);
            categoryManager.Delete(result);
            //categoryManager.Delete(category); 
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(int categoryId)
        {
            var result = categoryManager.GetById(categoryId);
            return View(result);
        }

        [HttpPost]
        public ActionResult Update(Category category)
        {
            var result = categoryManager.Update(category);
            return RedirectToAction("Index");
        }


    }
}

MvcProjectCamp/Controllers/CategoryController.cs
using Business.Abstract;
using Business.ValidationRules.FluentValidation;
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());


        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetAll()
        {
            var result = categoryManager.GetAll();
            return View(result);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Category category)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult validationResult = categoryValidator.Validate(category);
            if (validationResult.IsValid)
            {
                categoryManager.Add(category);
                return RedirectToAction("GetAll");
            }
            else
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MvcProjectCamp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MvcProjectCamp/Controllers/StatisticsController.cs
using DataAccessLayer.Concrete.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
    public class StatisticsController : Controller
    {
        Context _Context = new Context();

        // GET: Statistics
        public ActionResult Index()
        {
            var result1 = _Context.Categories.Count().ToString();
            ViewBag.result1 = result1;

            var result2 = _Context.Headings.Count(c => c.CategoryId == 17).ToString();
            ViewBag.result2 = result2;

            var result3 = (from c in _Context.Writers select c.WriterName.ToLower().IndexOf("a")).Count().ToString();
            ViewBag.result3 = result3;

            var result4 = _Context.Categories.Where(x => x.CategoryId == _Context.Headings.GroupBy(c => c.CategoryId).OrderByDescending(c => c.Count()).Select(c => c.Key).FirstOrDefault()).Select(x => x.CategoryName).FirstOrDefault();
            ViewBag.result4 = result4;

            var result5 = _Context.Categories.Count(x => x.CategoryStatus == true) - _Context.Categories.Count(x => x.CategoryStatus == false);
            ViewBag.result5 = result5;

            return View();
        }
    }
}

MvcProjectCamp/Views/AdminCategory/Add.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
@using (Html.BeginForm("Add", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(c => c.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.CategoryName)
        <br /><br />

        @Html.Label("Açıklamayı yazınız")
        @Html.TextAreaFor(c => c.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.CategoryDescription)
        <br /><br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

MvcProjectCamp/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@using Core.Utilities.Results.Abstract

@model IDataResult<List<Category>>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <div><tr>
        <th><b>#</b></th>
        <th><b>Kategori Adı</b></th>
        <th><b>Sil</b></th>
        <th><b>Güncelle</b></th>
        <th><b>Başlıklar</b></th>
    </tr></div>
    @foreach (var item in Model.Data)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
            <td><a href="/AdminCategory/Delete?categoryId=@item.CategoryId" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/Update?categoryId=@item.CategoryId" class="btn btn-warning">Güncelle</a></td>
            <td><a herf="#" class="btn btn-primary">Başlıklar</a></td>
        </tr>
    }
</table>
<br />
<a href="/AdminCategory/Add" class="btn btn-info">Yeni Kategori</a>

MvcProjectCamp/Views/AdminCategory/Update.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
@using (Html.BeginForm("Update", "AdminCategory", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori Id")
    @Html.TextBoxFor(c => c.CategoryId, new { @class = "form-control" })
    <br /><br />
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(c => c.CategoryName, new { @class = "form-control" })
    <br /><br />
    @Html.Label("Açıklamayı yazınız")
    @Html.TextAreaFor(c => c.CategoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}

MvcProjectCamp/Views/Category/Add.cshtml
@model EntityLayer.Concrete.Category

@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h1>Yeni bir kategori ekleme sayfası</h1>
<br />
@using (Html.BeginForm("Add", "Category", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(c => c.CategoryName)
    @Html.ValidationMessageFor(c => c.CategoryName)
    <br /><br />

    @Html.Label("Açıklamayı yazınız")
    @Html.TextBoxFor(c => c.CategoryDescription)
    @Html.ValidationMessageFor(c => c.CategoryDescription)
    <br /><br />
    <button class="btn btn-info">Kaydet</button>
</div>
}

MvcProjectCamp/Views/Category/GetAll.cshtml
@using EntityLayer.Concrete
@using Core.Utilities.Results.Abstract

@model IDataResult<List<Category>>

@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<br />
<h3> Mvc Kamp Tablo Örneği - Kategori </h3>
<br />
<table class="table table-bordered">
    <tr>
        <th><b>Id</b></th>
        <th><b>Kategori Adı</b></th>
        <th><b>Açıklama</b></th>
        <th><b>Durum</b></th>
    </tr>
    @foreach (var item in Model.Data)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
            <td>@item.CategoryDescription</td>
            <td>@item.CategoryStatus</td>
        </tr>
    }
</table>

MvcProjectCamp/Views/Category/Index.cshtml
@{
    Layout = null;
}

<br />
<h3> Mvc Kamp Tablo Örneği - Kategori </h3>
<br />
<table>
    <tr>
        <th><b>Id</b></th>
        <th><b>Kategori Adı</b></th>
        <th><b>Açıklama</b></th>
        <th><b>Durum</b></th>
    </tr>
    <tr>
        <th>1</th>
        <th>Eğitim</th>
        <th>Bi şeyler bi şeyler</th>
        <th>true</th>
    </tr>
    <tr>
        <th>2</th>
        <th>Spor</th>
        <th>Bi şeyler bi şeyler</th>
        <th>true</th>
    </tr>
</table>

MvcProjectCamp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MvcProjectCamp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MvcProjectCamp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MvcProjectCamp/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>AdminLTE 3 | Dashboard 3</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/Themes/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Themes/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/Themes/AdminLTE-3.0.4/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/Themes/AdminLTE-3.0.4/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Kategoriler
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/widgets.html" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Başlıklar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Yazarlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Grafikler
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/charts/chartjs.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/flot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/inline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 3</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    Hakkımızda
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    İletişim & Mesajlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Yazılar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/calendar.html" class="nav-link">
                                <i class="nav-icon fas fa-calendar-alt"></i>
                                <p>
                                    Yetkilendirmeler
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/gallery.html" class="nav-link">
                                <i class="nav-icon far fa-image"></i>
                                <p>
                                    Galeri
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-envelope"></i>
                                <p>
                                    Hata Sayfaları
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Siteye Git
                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-apple-alt"></i>
                                <p>
                                    Çıkış yap
                                </p>
                            </a>

                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                @RenderBody()
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/Themes/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Themes/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/Themes/AdminLTE-3.0.4/dist/js/adminlte.js"></script>
    <!-- OPTIONAL SCRIPTS -->
    <script src="~/Themes/AdminLTE-3.0.4/plugins/chart.js/Chart.min.js"></script>
    <script src="~/Themes/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/Themes/AdminLTE-3.0.4/dist/js/pages/dashboard3.js"></script>
</body>
</html>

MvcProjectCamp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcProjectCamp/Views/Statistics/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<br />
<br />
<div class="container">
    <div class="row">

        <div class="col-md-4">
            <div class="card text-white bg-success mb-3" style="max-width: 18rem;">               
                <img src="~/Images/image.jfif" class="card-img-top">
                <div class="card-header"> Toplam Kategori Sayısı </div>
                <div class="card-body">
                    <h5 class="card-title"><b> @ViewBag.result1 </b></h5>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                <img src="~/Images/image.jfif" class="card-img-top">
                <div class="card-header"> Yazılım Kategorisine Ait Başlık Sayısı </div>
                <div class="card-body">
                    <h5 class="card-title"><b> @ViewBag.result2 </b></h5>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card text-dark bg-warning mb-3" style="max-width: 18rem;">
                <img src="~/Images/image.jfif" class="card-img-top">
                <div class="card-header"> İsminde "a" Harfi Olan Yazar Sayısı </div>
                <div class="card-body">
                    <h5 class="card-title"><b> @ViewBag.result3 </b></h5>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card text-dark bg-info mb-3" style="max-width: 18rem;">
                <img src="~/Images/image.jfif" class="card-img-top">
                <div class="card-header"> En Fazla Başlığa Sahip Kategori </div>
                <div class="card-body">
                    <h5 class="card-title"><b> @ViewBag.result4 </b></h5>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
                <img src="~/Images/image.jfif" class="card-img-top">
                <div class="card-header"> True - False Farkı </div>
                <div class="card-body">
                    <h5 class="card-title"><b> @ViewBag.result5 </b></h5>
                </div>
            </div>
        </div>
    </div>
</div>